---
platform: linux

inputs:
- name: interpolated-creds
- name: files

outputs:
- name: interpolated-files

run:
  path: sh
  args:
  - -euc
  - |
    cp -r files/* interpolated-files/
    cp -r interpolated-creds/* interpolated-files/
