---
set-up-job: &set-up-job
  do:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: config
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: credhub_admin
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca-cert))
      PREFIX: '/fetch-dependencies/'
      SKIP_MISSING: true
    input_mapping:
      files: config
    output_mapping:
      interpolated-files: interpolated-creds
  - task: merge-files
    image: platform-automation-image
    file: config/tasks/merge-files/task.yml
    input_mapping:
      files: config

resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: config
  type: git
  source:
    private_key: ((github_private_key))
    uri: git@github.com:crsimmons/pks-azure.git
    branch: master

- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    sort_by: semver

- name: platform-automation-tasks
  type: azure-blobstore
  source:
    <<: &azure-params
      storage_account_name: ((storage_account_name))
      storage_account_key: ((storage_account_key))
      container: pivnet
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: azure-blobstore
  source:
    <<: *azure-params
    regexp: platform-automation-image-(.*).tgz

- name: opsman-product
  type: azure-blobstore
  source:
    <<: *azure-params
    regexp: ops-manager-azure-(.*).yml

- name: pks-product
  type: azure-blobstore
  source:
    <<: *azure-params
    regexp: pivotal-container-service-(.*).pivotal

- name: pks-stemcell
  type: azure-blobstore
  source:
    <<: *azure-params
    regexp: pks-stemcells/bosh-stemcell-(.*)-azure-hyperv-ubuntu-xenial-go_agent.tgz

- name: daily
  type: time
  source:
    interval: 24h

jobs:
- name: fetch-platform-automation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - in_parallel:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz

- name: fetch-opsman
  plan:
  - *set-up-job
  - task: download-opsman-image
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-configs/opsman.yml
    input_mapping:
      config: interpolated-files
  - in_parallel:
    - put: opsman-product
      params:
        file: downloaded-product/*

- name: fetch-pks
  plan:
  - *set-up-job
  - task: download-pks-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-configs/pks.yml
    input_mapping:
      config: interpolated-files
    output_mapping:
      downloaded-stemcell: pks-stemcell
  - in_parallel:
      - put: pks-product
        params:
          file: downloaded-product/*.pivotal
      - put: pks-stemcell
        params:
          file: pks-stemcell/*.tgz
